//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Models.Components;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    
    public class GetResponses200Hub
    {

        /// <summary>
        /// Whether this hub is visible on the home screen<br/>
        /// 
        /// <remarks>
        ///   - all: Visible to all users<br/>
        ///   - none: Visible to no users<br/>
        ///   - admin: Visible to only admin users<br/>
        ///   - shared: Visible to shared users<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("homeVisibility")]
        public Models.Components.HomeVisibility? HomeVisibility { get; set; }

        /// <summary>
        /// The identifier for this hub
        /// </summary>
        [JsonProperty("identifier")]
        public string? Identifier { get; set; }

        /// <summary>
        /// Whether this hub is visible to admin user home
        /// </summary>
        [JsonProperty("promotedToOwnHome")]
        public bool? PromotedToOwnHome { get; set; }

        /// <summary>
        /// Whether this hub is promoted to all for recommendations
        /// </summary>
        [JsonProperty("promotedToRecommended")]
        public bool? PromotedToRecommended { get; set; }

        /// <summary>
        /// Whether this hub is visible to shared user&apos;s home
        /// </summary>
        [JsonProperty("promotedToSharedHome")]
        public bool? PromotedToSharedHome { get; set; }

        /// <summary>
        /// The visibility of this hub in recommendations:<br/>
        /// 
        /// <remarks>
        ///   - all: Visible to all users<br/>
        ///   - none: Visible to no users<br/>
        ///   - admin: Visible to only admin users<br/>
        ///   - shared: Visible to shared users<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("recommendationsVisibility")]
        public Models.Components.RecommendationsVisibility? RecommendationsVisibility { get; set; }

        /// <summary>
        /// The title of this hub
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; }
    }
}