//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Whether this hub is visible on the home screen<br/>
    /// 
    /// <remarks>
    ///   - all: Visible to all users<br/>
    ///   - none: Visible to no users<br/>
    ///   - admin: Visible to only admin users<br/>
    ///   - shared: Visible to shared users<br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum HomeVisibility
    {
        [JsonProperty("all")]
        All,
        [JsonProperty("none")]
        None,
        [JsonProperty("admin")]
        Admin,
        [JsonProperty("shared")]
        Shared,
    }

    public static class HomeVisibilityExtension
    {
        public static string Value(this HomeVisibility value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static HomeVisibility ToEnum(this string value)
        {
            foreach(var field in typeof(HomeVisibility).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is HomeVisibility)
                    {
                        return (HomeVisibility)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum HomeVisibility");
        }
    }

}