//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Models.Components;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class MediaContainerWithArtworkMetadata
    {

        /// <summary>
        /// The title of the item
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; }

        [JsonProperty("type")]
        public MediaContainerWithArtworkType? Type { get; set; }

        /// <summary>
        /// The path to the artwork
        /// </summary>
        [JsonProperty("key")]
        public string? Key { get; set; }

        [JsonProperty("additionalProperties")]
        public Dictionary<string, object>? AdditionalProperties { get; set; }
    }
}