//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The location of the client
    /// </summary>
    public enum SessionLocation
    {
        [JsonProperty("lan")]
        Lan,
        [JsonProperty("wan")]
        Wan,
    }

    public static class SessionLocationExtension
    {
        public static string Value(this SessionLocation value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static SessionLocation ToEnum(this string value)
        {
            foreach(var field in typeof(SessionLocation).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is SessionLocation)
                    {
                        return (SessionLocation)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum SessionLocation");
        }
    }

}