//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Models.Components;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Information about the playback session
    /// </summary>
    public class Session
    {

        /// <summary>
        /// The bandwidth used by this client&apos;s playback in kbps
        /// </summary>
        [JsonProperty("bandwidth")]
        public long? Bandwidth { get; set; }

        /// <summary>
        /// The id of the playback session
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The location of the client
        /// </summary>
        [JsonProperty("location")]
        public SessionLocation? Location { get; set; }
    }
}