//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Models.Components;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class SlashGetResponses200MediaContainer
    {

        /// <summary>
        /// The flavors of directory found here:<br/>
        /// 
        /// <remarks>
        ///   - Primary: (e.g. all, On Deck) These are still used in some clients to provide &quot;shortcuts&quot; to subsets of media. However, with the exception of On Deck, all of them can be created by media queries, and the desire is to allow these to be customized by users.<br/>
        ///   - Secondary: These are marked with `&quot;secondary&quot;: true` and were used by old clients to provide nested menus allowing for primative (but structured) navigation.<br/>
        ///   - Special: There is a By Folder entry which allows browsing the media by the underlying filesystem structure, and there&apos;s a completely obsolete entry marked `&quot;search&quot;: true` which used to be used to allow clients to build search dialogs on the fly.
        /// </remarks>
        /// </summary>
        [JsonProperty("content")]
        public string? Content { get; set; }

        [JsonProperty("allowSync")]
        public bool? AllowSync { get; set; }

        [JsonProperty("art")]
        public string? Art { get; set; }

        [JsonProperty("Directory")]
        public List<Models.Components.Metadata>? Directory { get; set; }

        [JsonProperty("identifier")]
        public string? Identifier { get; set; }

        [JsonProperty("librarySectionID")]
        public long? LibrarySectionID { get; set; }

        [JsonProperty("mediaTagPrefix")]
        public string? MediaTagPrefix { get; set; }

        [JsonProperty("mediaTagVersion")]
        public long? MediaTagVersion { get; set; }

        [JsonProperty("size")]
        public long? Size { get; set; }

        [JsonProperty("sortAsc")]
        public bool? SortAsc { get; set; }

        [JsonProperty("thumb")]
        public string? Thumb { get; set; }

        [JsonProperty("title1")]
        public string? Title1 { get; set; }

        [JsonProperty("viewGroup")]
        public string? ViewGroup { get; set; }

        [JsonProperty("viewMode")]
        public long? ViewMode { get; set; }
    }
}