//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace PlexAPI.Models.Requests
{
    using Newtonsoft.Json;
    using PlexAPI.Models.Requests;
    using PlexAPI.Utils;
    
    /// <summary>
    /// Devices
    /// </summary>
    public class GetDevicesResponseBody
    {

        [JsonProperty("MediaContainer")]
        public GetDevicesMediaContainer? MediaContainer { get; set; }
    }
}