//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace PlexAPI.Models.Requests
{
    using PlexAPI.Utils;
    
    public class GetFileHashRequest
    {

        /// <summary>
        /// This is the path to the local file, must be prefixed by `file://`
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=url")]
        public string Url { get; set; } = default!;

        /// <summary>
        /// Item type
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=type")]
        public double? Type { get; set; }
    }
}