
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace PlexAPI.Models.Requests
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// X-Plex-Client-Identifier is missing
    /// </summary>
    public class GetTokenResponseBody
    {

        [JsonProperty("errors")]
        public List<GetTokenErrors>? Errors { get; set; }
    }
}