//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Models.Requests;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    
    public class Country
    {

        /// <summary>
        /// Three letter code
        /// </summary>
        [JsonProperty("code")]
        public string? Code { get; set; }

        [JsonProperty("example")]
        public string? Example { get; set; }

        /// <summary>
        /// - `0`: The country is divided into regions, and following the key will lead to a list of regions.<br/>
        /// 
        /// <remarks>
        /// - `1`: The county is divided by postal codes, and an example code is returned in `example`.<br/>
        /// - `2`: The country has a single postal code, returned in `example`.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("flavor")]
        public Flavor? Flavor { get; set; }

        [JsonProperty("key")]
        public string? Key { get; set; }

        /// <summary>
        /// Three letter language code
        /// </summary>
        [JsonProperty("language")]
        public string? Language { get; set; }

        /// <summary>
        /// The title of the language
        /// </summary>
        [JsonProperty("languageTitle")]
        public string? LanguageTitle { get; set; }

        [JsonProperty("title")]
        public string? Title { get; set; }

        [JsonProperty("type")]
        public string? Type { get; set; }
    }
}