//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Setting that indicates if credits markers detection is enabled. (-1 = Library default, 0 = Disabled).
    /// </summary>
    public enum EnableCreditsMarkerGeneration
    {
        [JsonProperty("-1")]
        LibraryDefault,
        [JsonProperty("0")]
        Disabled,
    }

    public static class EnableCreditsMarkerGenerationExtension
    {
        public static string Value(this EnableCreditsMarkerGeneration value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static EnableCreditsMarkerGeneration ToEnum(this string value)
        {
            foreach(var field in typeof(EnableCreditsMarkerGeneration).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is EnableCreditsMarkerGeneration)
                    {
                        return (EnableCreditsMarkerGeneration)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum EnableCreditsMarkerGeneration");
        }
    }

}