//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Models.Requests;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class GetAllLibrariesMediaContainer
    {

        /// <summary>
        /// Number of media items returned in this response.
        /// </summary>
        [JsonProperty("size")]
        public int Size { get; set; } = default!;

        /// <summary>
        /// Indicates whether syncing is allowed.
        /// </summary>
        [JsonProperty("allowSync")]
        public bool AllowSync { get; set; } = default!;

        /// <summary>
        /// The primary title of the media container.
        /// </summary>
        [JsonProperty("title1")]
        public string Title1 { get; set; } = default!;

        [JsonProperty("Directory")]
        public List<GetAllLibrariesDirectory>? Directory { get; set; }
    }
}