//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Models.Requests;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class GetBandwidthStatisticsMediaContainer
    {

        [JsonProperty("size")]
        public int? Size { get; set; }

        [JsonProperty("Device")]
        public List<GetBandwidthStatisticsDevice>? Device { get; set; }

        [JsonProperty("Account")]
        public List<GetBandwidthStatisticsAccount>? Account { get; set; }

        [JsonProperty("StatisticsBandwidth")]
        public List<StatisticsBandwidth>? StatisticsBandwidth { get; set; }
    }
}