//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The type of media to retrieve or filter by.<br/>
    /// 
    /// <remarks>
    /// 1 = movie<br/>
    /// 2 = show<br/>
    /// 3 = season<br/>
    /// 4 = episode<br/>
    /// E.g. A movie library will not return anything with type 3 as there are no seasons for movie libraries<br/>
    /// 
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class GetGenresLibraryQueryParamType : IEquatable<GetGenresLibraryQueryParamType>
    {
        public static readonly GetGenresLibraryQueryParamType Movie = new GetGenresLibraryQueryParamType(1);
        public static readonly GetGenresLibraryQueryParamType TvShow = new GetGenresLibraryQueryParamType(2);
        public static readonly GetGenresLibraryQueryParamType Season = new GetGenresLibraryQueryParamType(3);
        public static readonly GetGenresLibraryQueryParamType Episode = new GetGenresLibraryQueryParamType(4);
        public static readonly GetGenresLibraryQueryParamType Artist = new GetGenresLibraryQueryParamType(5);
        public static readonly GetGenresLibraryQueryParamType Album = new GetGenresLibraryQueryParamType(6);
        public static readonly GetGenresLibraryQueryParamType Track = new GetGenresLibraryQueryParamType(7);
        public static readonly GetGenresLibraryQueryParamType PhotoAlbum = new GetGenresLibraryQueryParamType(8);
        public static readonly GetGenresLibraryQueryParamType Photo = new GetGenresLibraryQueryParamType(9);

        private static readonly Dictionary <long, GetGenresLibraryQueryParamType> _knownValues =
            new Dictionary <long, GetGenresLibraryQueryParamType> ()
            {
                [1] = Movie,
                [2] = TvShow,
                [3] = Season,
                [4] = Episode,
                [5] = Artist,
                [6] = Album,
                [7] = Track,
                [8] = PhotoAlbum,
                [9] = Photo
            };

        private static readonly ConcurrentDictionary<long, GetGenresLibraryQueryParamType> _values =
            new ConcurrentDictionary<long, GetGenresLibraryQueryParamType>(_knownValues);

        private GetGenresLibraryQueryParamType(long value)
        {
            Value = value;
        }

        public long Value { get; }

        public static GetGenresLibraryQueryParamType Of(long value)
        {
            return _values.GetOrAdd(value, _ => new GetGenresLibraryQueryParamType(value));
        }

        public static implicit operator GetGenresLibraryQueryParamType(long value) => Of(value);
        public static implicit operator long(GetGenresLibraryQueryParamType getgenreslibraryqueryparamtype) => getgenreslibraryqueryparamtype.Value;

        public static GetGenresLibraryQueryParamType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GetGenresLibraryQueryParamType);

        public bool Equals(GetGenresLibraryQueryParamType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}