//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class GetLibraryItemsLibraryResponseType : IEquatable<GetLibraryItemsLibraryResponseType>
    {
        public static readonly GetLibraryItemsLibraryResponseType CoverPoster = new GetLibraryItemsLibraryResponseType("coverPoster");
        public static readonly GetLibraryItemsLibraryResponseType Background = new GetLibraryItemsLibraryResponseType("background");
        public static readonly GetLibraryItemsLibraryResponseType Snapshot = new GetLibraryItemsLibraryResponseType("snapshot");
        public static readonly GetLibraryItemsLibraryResponseType ClearLogo = new GetLibraryItemsLibraryResponseType("clearLogo");

        private static readonly Dictionary <string, GetLibraryItemsLibraryResponseType> _knownValues =
            new Dictionary <string, GetLibraryItemsLibraryResponseType> ()
            {
                ["coverPoster"] = CoverPoster,
                ["background"] = Background,
                ["snapshot"] = Snapshot,
                ["clearLogo"] = ClearLogo
            };

        private static readonly ConcurrentDictionary<string, GetLibraryItemsLibraryResponseType> _values =
            new ConcurrentDictionary<string, GetLibraryItemsLibraryResponseType>(_knownValues);

        private GetLibraryItemsLibraryResponseType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static GetLibraryItemsLibraryResponseType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new GetLibraryItemsLibraryResponseType(value));
        }

        public static implicit operator GetLibraryItemsLibraryResponseType(string value) => Of(value);
        public static implicit operator string(GetLibraryItemsLibraryResponseType getlibraryitemslibraryresponsetype) => getlibraryitemslibraryresponsetype.Value;

        public static GetLibraryItemsLibraryResponseType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GetLibraryItemsLibraryResponseType);

        public bool Equals(GetLibraryItemsLibraryResponseType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}