//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The type of media content in the Plex library. This can represent videos, music, or photos.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public enum GetMediaMetaDataType
    {
        [JsonProperty("movie")]
        Movie,
        [JsonProperty("show")]
        TvShow,
        [JsonProperty("season")]
        Season,
        [JsonProperty("episode")]
        Episode,
        [JsonProperty("artist")]
        Artist,
        [JsonProperty("album")]
        Album,
        [JsonProperty("track")]
        Track,
        [JsonProperty("photoalbum")]
        PhotoAlbum,
        [JsonProperty("photo")]
        Photo,
        [JsonProperty("collection")]
        Collection,
    }

    public static class GetMediaMetaDataTypeExtension
    {
        public static string Value(this GetMediaMetaDataType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetMediaMetaDataType ToEnum(this string value)
        {
            foreach(var field in typeof(GetMediaMetaDataType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetMediaMetaDataType)
                    {
                        return (GetMediaMetaDataType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetMediaMetaDataType");
        }
    }

}