//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The type of media content in the Plex library. This can represent videos, music, or photos.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class GetSearchAllLibrariesType : IEquatable<GetSearchAllLibrariesType>
    {
        public static readonly GetSearchAllLibrariesType Movie = new GetSearchAllLibrariesType("movie");
        public static readonly GetSearchAllLibrariesType TvShow = new GetSearchAllLibrariesType("show");
        public static readonly GetSearchAllLibrariesType Season = new GetSearchAllLibrariesType("season");
        public static readonly GetSearchAllLibrariesType Episode = new GetSearchAllLibrariesType("episode");
        public static readonly GetSearchAllLibrariesType Artist = new GetSearchAllLibrariesType("artist");
        public static readonly GetSearchAllLibrariesType Album = new GetSearchAllLibrariesType("album");
        public static readonly GetSearchAllLibrariesType Track = new GetSearchAllLibrariesType("track");
        public static readonly GetSearchAllLibrariesType PhotoAlbum = new GetSearchAllLibrariesType("photoalbum");
        public static readonly GetSearchAllLibrariesType Photo = new GetSearchAllLibrariesType("photo");
        public static readonly GetSearchAllLibrariesType Collection = new GetSearchAllLibrariesType("collection");

        private static readonly Dictionary <string, GetSearchAllLibrariesType> _knownValues =
            new Dictionary <string, GetSearchAllLibrariesType> ()
            {
                ["movie"] = Movie,
                ["show"] = TvShow,
                ["season"] = Season,
                ["episode"] = Episode,
                ["artist"] = Artist,
                ["album"] = Album,
                ["track"] = Track,
                ["photoalbum"] = PhotoAlbum,
                ["photo"] = Photo,
                ["collection"] = Collection
            };

        private static readonly ConcurrentDictionary<string, GetSearchAllLibrariesType> _values =
            new ConcurrentDictionary<string, GetSearchAllLibrariesType>(_knownValues);

        private GetSearchAllLibrariesType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static GetSearchAllLibrariesType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new GetSearchAllLibrariesType(value));
        }

        public static implicit operator GetSearchAllLibrariesType(string value) => Of(value);
        public static implicit operator string(GetSearchAllLibrariesType getsearchalllibrariestype) => getsearchalllibrariestype.Value;

        public static GetSearchAllLibrariesType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GetSearchAllLibrariesType);

        public bool Equals(GetSearchAllLibrariesType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}