//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class GetTokenDetailsStatus : IEquatable<GetTokenDetailsStatus>
    {
        public static readonly GetTokenDetailsStatus Online = new GetTokenDetailsStatus("online");
        public static readonly GetTokenDetailsStatus Offline = new GetTokenDetailsStatus("offline");

        private static readonly Dictionary <string, GetTokenDetailsStatus> _knownValues =
            new Dictionary <string, GetTokenDetailsStatus> ()
            {
                ["online"] = Online,
                ["offline"] = Offline
            };

        private static readonly ConcurrentDictionary<string, GetTokenDetailsStatus> _values =
            new ConcurrentDictionary<string, GetTokenDetailsStatus>(_knownValues);

        private GetTokenDetailsStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static GetTokenDetailsStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new GetTokenDetailsStatus(value));
        }

        public static implicit operator GetTokenDetailsStatus(string value) => Of(value);
        public static implicit operator string(GetTokenDetailsStatus gettokendetailsstatus) => gettokendetailsstatus.Value;

        public static GetTokenDetailsStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GetTokenDetailsStatus);

        public bool Equals(GetTokenDetailsStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}