//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The status of this update.<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// - available - This release is available<br/>
    /// - downloading - This release is downloading<br/>
    /// - downloaded - This release has been downloaded<br/>
    /// - installing - This release is installing<br/>
    /// - tonight - This release will be installed tonight<br/>
    /// - skipped - This release has been skipped<br/>
    /// - error - This release has an error<br/>
    /// - notify - This release is only notifying it is available (typically because it cannot be installed on this setup)<br/>
    /// - done - This release is complete<br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum GetUpdatesStatusState
    {
        [JsonProperty("available")]
        Available,
        [JsonProperty("downloading")]
        Downloading,
        [JsonProperty("downloaded")]
        Downloaded,
        [JsonProperty("installing")]
        Installing,
        [JsonProperty("tonight")]
        Tonight,
        [JsonProperty("skipped")]
        Skipped,
        [JsonProperty("error")]
        Error,
        [JsonProperty("notify")]
        Notify,
        [JsonProperty("done")]
        Done,
    }

    public static class GetUpdatesStatusStateExtension
    {
        public static string Value(this GetUpdatesStatusState value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetUpdatesStatusState ToEnum(this string value)
        {
            foreach(var field in typeof(GetUpdatesStatusState).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetUpdatesStatusState)
                    {
                        return (GetUpdatesStatusState)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetUpdatesStatusState");
        }
    }

}