//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    
    /// <summary>
    /// The Plex library visibility setting
    /// </summary>
    public enum Hidden
    {
        Visible = 0,
        ExcludeHomeScreen = 1,
        ExcludeHomeScreenAndGlobalSearch = 2,
    }

}