//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    
    public class MarkUnplayedRequest
    {

        /// <summary>
        /// The media key to mark as Unplayed
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=key")]
        public double Key { get; set; } = default!;
    }
}