//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    
    /// <summary>
    /// Login credentials
    /// </summary>
    public class PostUsersSignInDataRequestBody
    {

        [SpeakeasyMetadata("form:name=login")]
        public string Login { get; set; } = default!;

        [SpeakeasyMetadata("form:name=password")]
        public string Password { get; set; } = default!;

        [SpeakeasyMetadata("form:name=rememberMe")]
        public bool? RememberMe { get; set; } = false;
    }
}