//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// String representation of subscriptionActive
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class PostUsersSignInDataAuthenticationStatus : IEquatable<PostUsersSignInDataAuthenticationStatus>
    {
        public static readonly PostUsersSignInDataAuthenticationStatus Inactive = new PostUsersSignInDataAuthenticationStatus("Inactive");
        public static readonly PostUsersSignInDataAuthenticationStatus Active = new PostUsersSignInDataAuthenticationStatus("Active");

        private static readonly Dictionary <string, PostUsersSignInDataAuthenticationStatus> _knownValues =
            new Dictionary <string, PostUsersSignInDataAuthenticationStatus> ()
            {
                ["Inactive"] = Inactive,
                ["Active"] = Active
            };

        private static readonly ConcurrentDictionary<string, PostUsersSignInDataAuthenticationStatus> _values =
            new ConcurrentDictionary<string, PostUsersSignInDataAuthenticationStatus>(_knownValues);

        private PostUsersSignInDataAuthenticationStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static PostUsersSignInDataAuthenticationStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new PostUsersSignInDataAuthenticationStatus(value));
        }

        public static implicit operator PostUsersSignInDataAuthenticationStatus(string value) => Of(value);
        public static implicit operator string(PostUsersSignInDataAuthenticationStatus postuserssignindataauthenticationstatus) => postuserssignindataauthenticationstatus.Value;

        public static PostUsersSignInDataAuthenticationStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as PostUsersSignInDataAuthenticationStatus);

        public bool Equals(PostUsersSignInDataAuthenticationStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}