//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Indicates the network streaming protocol to be used for the transcode session: * &apos;http&apos; - include the file in the http response such as MKV streaming * &apos;hls&apos; - hls stream (RFC 8216) * &apos;dash&apos; - dash stream (ISO/IEC 23009-1:2022)<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public enum StartTranscodeSessionQueryParamProtocol
    {
        [JsonProperty("http")]
        Http,
        [JsonProperty("hls")]
        Hls,
        [JsonProperty("dash")]
        Dash,
    }

    public static class StartTranscodeSessionQueryParamProtocolExtension
    {
        public static string Value(this StartTranscodeSessionQueryParamProtocol value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static StartTranscodeSessionQueryParamProtocol ToEnum(this string value)
        {
            foreach(var field in typeof(StartTranscodeSessionQueryParamProtocol).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is StartTranscodeSessionQueryParamProtocol)
                    {
                        return (StartTranscodeSessionQueryParamProtocol)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum StartTranscodeSessionQueryParamProtocol");
        }
    }

}