workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    plexapi:
        inputs:
            - location: registry.speakeasyapi.dev/plexapi/plexapi/plexapi:main
targets:
    plexcsharp:
        target: csharp
        source: plexapi
        publish:
            nuget:
                apiKey: $nuget_api_key
        codeSamples:
            labelOverride: 
                fixedValue: PlexCSharp
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-csharp-plexcsharp
